### ISSUE TITLE
style guide

### ISSUE THREAD

**Issue by aaronArinder** [aaronArinder/welby#20]
#### Problem
We need to have a unified style.

#### Solution
Create a style guide for us to follow.

#### To-dos
- [ ] research how to create a style guide
- [ ] find similar style guides out there
- [ ] get a meeting together to finalize whatever style guide we come up with
